name: End to End test for Aifinyo Web-Application
on:
  push:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check for merge conflicts
        run: |
          git fetch origin main
          ! git diff --check $(git merge-base main HEAD)
        continue-on-error: true
      - name: Cypress run with env
        uses: cypress-io/github-action@v6
        env:
          APP_ID: k20270727
          APP_SYS: billomat 
          CYPRESS_RECORD_KEY: ${{secrets.CYPRESS_RECORD_KEY}}
        with:
            record: false
            headed: true
            spec: cypress/e2e/billomat-frontend/1_Invoices/**/*